/**
 * @fileoverview Sidebar configuration generator
 * @module generators/SidebarGenerator
 */

const { getChapterName } = require('../config/chapters');
const { sortChapterKeys, extractLabelFromProgramId } = require('../utils/helpers');

/**
 * Generator for Docusaurus sidebar configuration
 */
class SidebarGenerator {
  /**
   * Create a sidebar generator
   * @param {Object} config - Application configuration
   */
  constructor(config) {
    this.config = config;
  }

  /**
   * Generate sidebar configuration content
   * @param {Map<string, Set<string>>} byChapter - Map of chapter -> Set of program IDs
   * @returns {string} JavaScript module content for sidebars.js
   */
  generate(byChapter) {
    const categories = Array.from(byChapter.keys())
      .sort(sortChapterKeys)
      .map(chapterNum => this.generateCategory(chapterNum, byChapter.get(chapterNum)));

    return `/**
 * Auto-generated sidebar configuration
 * Generated by: Applied QM Documentation Generator v${this.config.version}
 * Last updated: ${new Date().toISOString()}
 *
 * DO NOT EDIT MANUALLY - Changes will be overwritten on next generation
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '📖 Introduction',
    },
    {
      type: 'category',
      label: '📚 Programs by Chapter',
      collapsed: false,
      items: [
${categories.map(cat => `        ${JSON.stringify(cat, null, 2).split('\n').join('\n        ')}`).join(',\n')},
      ],
    },
    {
      type: 'category',
      label: '🛠️ Developer Guide',
      collapsed: true,
      items: [
        { type: 'doc', id: 'developer-guide/index', label: 'Overview' },
        {
          type: 'category',
          label: 'Configuration',
          collapsed: true,
          items: [
            { type: 'doc', id: 'developer-guide/config/index', label: 'Config Module' },
          ],
        },
        {
          type: 'category',
          label: 'Utilities',
          collapsed: true,
          items: [
            { type: 'doc', id: 'developer-guide/utils/index', label: 'Utils Module' },
          ],
        },
        {
          type: 'category',
          label: 'Generators',
          collapsed: true,
          items: [
            { type: 'doc', id: 'developer-guide/generators/index', label: 'Generators Module' },
          ],
        },
        {
          type: 'category',
          label: 'Services',
          collapsed: true,
          items: [
            { type: 'doc', id: 'developer-guide/services/index', label: 'Services Module' },
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
`;
  }

  /**
   * Generate a chapter category for the sidebar
   * @param {string} chapterNum - Chapter number or 'utilities'
   * @param {Set<string>} programs - Set of program IDs
   * @returns {Object} Sidebar category object
   */
  generateCategory(chapterNum, programs) {
    const items = Array.from(programs)
      .sort()
      .map(programId => this.generateItem(chapterNum, programId));

    const label = chapterNum === 'utilities'
      ? `🔧 ${getChapterName(chapterNum)}`
      : `Ch ${parseInt(chapterNum, 10)}: ${getChapterName(chapterNum)}`;

    return {
      type: 'category',
      label,
      collapsed: true,
      items,
    };
  }

  /**
   * Generate a single program item for the sidebar
   * @param {string} chapterNum - Chapter number or 'utilities'
   * @param {string} programId - Program ID
   * @returns {Object} Sidebar doc item object
   */
  generateItem(chapterNum, programId) {
    const folder = chapterNum === 'utilities' ? 'utilities' : `chapter${chapterNum}`;
    const label = extractLabelFromProgramId(programId);

    return {
      type: 'doc',
      id: `${folder}/${programId}/index`,
      label,
    };
  }
}

module.exports = SidebarGenerator;
