/**
 * Auto-generated sidebar configuration
 * Generated by: Applied QM Documentation Generator v2.1
 * Last updated: 2025-12-23T20:58:04.420Z
 *
 * DO NOT EDIT MANUALLY - Changes will be overwritten on next generation
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '📖 Introduction',
    },
    {
      type: 'category',
      label: '📚 Programs by Chapter',
      collapsed: false,
      items: [
        {
          "type": "category",
          "label": "Ch 1: Introduction to Quantum Mechanics",
          "collapsed": true,
          "items": [
            {
              "type": "doc",
              "id": "chapter1/Chapt1Exercise8/Chapt1Exercise8_matlab",
              "label": "Ex8-matlab"
            },
            {
              "type": "doc",
              "id": "chapter1/Chapt1Fig10/Chapt1Fig10_matlab",
              "label": "Fig10-matlab"
            },
            {
              "type": "doc",
              "id": "chapter1/Chapt1Fig8/Chapt1Fig8_matlab",
              "label": "Fig8-matlab"
            }
          ]
        },
        {
          "type": "category",
          "label": "Ch 2: Schrödinger Equation",
          "collapsed": true,
          "items": [
            {
              "type": "doc",
              "id": "chapter2/Chapt2Fig2/Chapt2Fig2_matlab",
              "label": "Fig2-matlab"
            },
            {
              "type": "doc",
              "id": "chapter2/Chapt2Fig24/Chapt2Fig24_matlab",
              "label": "Fig24-matlab"
            },
            {
              "type": "doc",
              "id": "chapter2/Chapt2Fig3a/Chapt2Fig3a_matlab",
              "label": "Fig3a-matlab"
            },
            {
              "type": "doc",
              "id": "chapter2/Chapt2Fig3b/Chapt2Fig3b_matlab",
              "label": "Fig3b-matlab"
            },
            {
              "type": "doc",
              "id": "chapter2/Chapt2Fig4/Chapt2Fig4_matlab",
              "label": "Fig4-matlab"
            }
          ]
        },
        {
          "type": "category",
          "label": "Ch 3: Quantum Wells and Barriers",
          "collapsed": true,
          "items": [
            {
              "type": "doc",
              "id": "chapter3/Chapt3Exercise7/Chapt3Exercise7_matlab",
              "label": "Ex7-matlab"
            },
            {
              "type": "doc",
              "id": "chapter3/Chapt3Fig14/Chapt3Fig14_matlab",
              "label": "Fig14-matlab"
            }
          ]
        },
        {
          "type": "category",
          "label": "Ch 4: Harmonic Oscillator",
          "collapsed": true,
          "items": [
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise2a/Chapt4Exercise2a_matlab",
              "label": "Ex2a-matlab"
            },
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise2b/Chapt4Exercise2b_matlab",
              "label": "Ex2b-matlab"
            },
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise3a/Chapt4Exercise3a_matlab",
              "label": "Ex3a-matlab"
            },
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise3b/Chapt4Exercise3b_matlab",
              "label": "Ex3b-matlab"
            },
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise4a/Chapt4Exercise4a_matlab",
              "label": "Ex4a-matlab"
            },
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise4b1/Chapt4Exercise4b1_matlab",
              "label": "Ex4b1-matlab"
            },
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise4b2/Chapt4Exercise4b2_matlab",
              "label": "Ex4b2-matlab"
            },
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise4b3/Chapt4Exercise4b3_matlab",
              "label": "Ex4b3-matlab"
            },
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise5/Chapt4Exercise5_matlab",
              "label": "Ex5-matlab"
            },
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise7a/Chapt4Exercise7a_matlab",
              "label": "Ex7a-matlab"
            },
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise7b/Chapt4Exercise7b_matlab",
              "label": "Ex7b-matlab"
            },
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise8/Chapt4Exercise8_matlab",
              "label": "Ex8-matlab"
            },
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise9/Chapt4Exercise9_matlab",
              "label": "Ex9-matlab"
            }
          ]
        },
        {
          "type": "category",
          "label": "Ch 5: Tunneling and Resonance",
          "collapsed": true,
          "items": [
            {
              "type": "doc",
              "id": "chapter5/Chapt5Exercise5/Chapt5Exercise5_matlab",
              "label": "Ex5-matlab"
            }
          ]
        },
        {
          "type": "category",
          "label": "Ch 6: Density of States",
          "collapsed": true,
          "items": [
            {
              "type": "doc",
              "id": "chapter6/Chapt6Exercise10/Chapt6Exercise10_matlab",
              "label": "Ex10-matlab"
            },
            {
              "type": "doc",
              "id": "chapter6/Chapt6Exercise4c/Chapt6Exercise4c_matlab",
              "label": "Ex4c-matlab"
            },
            {
              "type": "doc",
              "id": "chapter6/Chapt6Exercise4d/Chapt6Exercise4d_matlab",
              "label": "Ex4d-matlab"
            }
          ]
        },
        {
          "type": "category",
          "label": "Ch 7: Band Structure",
          "collapsed": true,
          "items": [
            {
              "type": "doc",
              "id": "chapter7/Chapt7Exercise3/Chapt7Exercise3_matlab",
              "label": "Ex3-matlab"
            },
            {
              "type": "doc",
              "id": "chapter7/Chapt7Fig3/Chapt7Fig3_matlab",
              "label": "Fig3-matlab"
            },
            {
              "type": "doc",
              "id": "chapter7/Chapt7Fig4a/Chapt7Fig4a_matlab",
              "label": "Fig4a-matlab"
            },
            {
              "type": "doc",
              "id": "chapter7/Chapt7Fig4b/Chapt7Fig4b_matlab",
              "label": "Fig4b-matlab"
            },
            {
              "type": "doc",
              "id": "chapter7/Chapt7Fig5a/Chapt7Fig5a_matlab",
              "label": "Fig5a-matlab"
            },
            {
              "type": "doc",
              "id": "chapter7/Chapt7Fig5b/Chapt7Fig5b_matlab",
              "label": "Fig5b-matlab"
            },
            {
              "type": "doc",
              "id": "chapter7/Chapt7Fig6a/Chapt7Fig6a_matlab",
              "label": "Fig6a-matlab"
            },
            {
              "type": "doc",
              "id": "chapter7/Chapt7Fig6a/Chapt7Fig6a_latex",
              "label": "Fig6a-latex"
            },
            {
              "type": "doc",
              "id": "chapter7/Chapt7Fig6a/Chapt7Fig6a_pdf",
              "label": "Fig6a-pdf"
            },
            {
              "type": "doc",
              "id": "chapter7/Chapt7Fig6b/Chapt7Fig6b_matlab",
              "label": "Fig6b-matlab"
            },
            {
              "type": "doc",
              "id": "chapter7/Chapt7Fig6b/Chapt7Fig6b_latex",
              "label": "Fig6b-latex"
            },
            {
              "type": "doc",
              "id": "chapter7/Chapt7Fig6b/Chapt7Fig6b_pdf",
              "label": "Fig6b-pdf"
            }
          ]
        },
        {
          "type": "category",
          "label": "Ch 8: Perturbation Theory",
          "collapsed": true,
          "items": [
            {
              "type": "doc",
              "id": "chapter8/Chapt8Exercise1b/Chapt8Exercise1b_matlab",
              "label": "Ex1b-matlab"
            },
            {
              "type": "doc",
              "id": "chapter8/Chapt8Exercise1b/Chapt8Exercise1b_latex",
              "label": "Ex1b-latex"
            },
            {
              "type": "doc",
              "id": "chapter8/Chapt8Exercise1b/Chapt8Exercise1b_pdf",
              "label": "Ex1b-pdf"
            },
            {
              "type": "doc",
              "id": "chapter8/Chapt8Exercise7a/Chapt8Exercise7a_matlab",
              "label": "Ex7a-matlab"
            },
            {
              "type": "doc",
              "id": "chapter8/Chapt8Exercise7a/Chapt8Exercise7a_latex",
              "label": "Ex7a-latex"
            },
            {
              "type": "doc",
              "id": "chapter8/Chapt8Exercise7a/Chapt8Exercise7a_pdf",
              "label": "Ex7a-pdf"
            },
            {
              "type": "doc",
              "id": "chapter8/Chapt8Exercise7b/Chapt8Exercise7b_matlab",
              "label": "Ex7b-matlab"
            },
            {
              "type": "doc",
              "id": "chapter8/Chapt8Exercise7b/Chapt8Exercise7b_latex",
              "label": "Ex7b-latex"
            },
            {
              "type": "doc",
              "id": "chapter8/Chapt8Exercise7b/Chapt8Exercise7b_pdf",
              "label": "Ex7b-pdf"
            },
            {
              "type": "doc",
              "id": "chapter8/Chapt8Fig14a/Chapt8Fig14a_matlab",
              "label": "Fig14a-matlab"
            },
            {
              "type": "doc",
              "id": "chapter8/Chapt8Fig14a/Chapt8Fig14a_latex",
              "label": "Fig14a-latex"
            },
            {
              "type": "doc",
              "id": "chapter8/Chapt8Fig14a/Chapt8Fig14a_pdf",
              "label": "Fig14a-pdf"
            },
            {
              "type": "doc",
              "id": "chapter8/Chapt8Fig14b/Chapt8Fig14b_matlab",
              "label": "Fig14b-matlab"
            },
            {
              "type": "doc",
              "id": "chapter8/Chapt8Fig14b/Chapt8Fig14b_latex",
              "label": "Fig14b-latex"
            },
            {
              "type": "doc",
              "id": "chapter8/Chapt8Fig14b/Chapt8Fig14b_pdf",
              "label": "Fig14b-pdf"
            },
            {
              "type": "doc",
              "id": "chapter8/Chapt8Fig15/Chapt8Fig15_matlab",
              "label": "Fig15-matlab"
            },
            {
              "type": "doc",
              "id": "chapter8/Chapt8Fig15/Chapt8Fig15_latex",
              "label": "Fig15-latex"
            },
            {
              "type": "doc",
              "id": "chapter8/Chapt8Fig15/Chapt8Fig15_pdf",
              "label": "Fig15-pdf"
            }
          ]
        },
        {
          "type": "category",
          "label": "Ch 9: Statistical Mechanics",
          "collapsed": true,
          "items": [
            {
              "type": "doc",
              "id": "chapter9/Chapt9Exercise1/Chapt9Exercise1_matlab",
              "label": "Ex1-matlab"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Exercise1/Chapt9Exercise1_latex",
              "label": "Ex1-latex"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Exercise1/Chapt9Exercise1_pdf",
              "label": "Ex1-pdf"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Exercise2/Chapt9Exercise2_matlab",
              "label": "Ex2-matlab"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Exercise2/Chapt9Exercise2_latex",
              "label": "Ex2-latex"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Exercise2/Chapt9Exercise2_pdf",
              "label": "Ex2-pdf"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Exercise3/Chapt9Exercise3_matlab",
              "label": "Ex3-matlab"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Exercise3/Chapt9Exercise3_latex",
              "label": "Ex3-latex"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Exercise3/Chapt9Exercise3_pdf",
              "label": "Ex3-pdf"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Exercise4/Chapt9Exercise4_matlab",
              "label": "Ex4-matlab"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Exercise4/Chapt9Exercise4_latex",
              "label": "Ex4-latex"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Exercise4/Chapt9Exercise4_pdf",
              "label": "Ex4-pdf"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Exercise5/Chapt9Exercise5_matlab",
              "label": "Ex5-matlab"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Exercise5/Chapt9Exercise5_latex",
              "label": "Ex5-latex"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Exercise5/Chapt9Exercise5_pdf",
              "label": "Ex5-pdf"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Fig6a1/Chapt9Fig6a1_matlab",
              "label": "Fig6a1-matlab"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Fig6a1/Chapt9Fig6a1_latex",
              "label": "Fig6a1-latex"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Fig6a1/Chapt9Fig6a1_pdf",
              "label": "Fig6a1-pdf"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Fig6a2/Chapt9Fig6a2_matlab",
              "label": "Fig6a2-matlab"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Fig6a2/Chapt9Fig6a2_latex",
              "label": "Fig6a2-latex"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Fig6a2/Chapt9Fig6a2_pdf",
              "label": "Fig6a2-pdf"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Fig6b/Chapt9Fig6b_matlab",
              "label": "Fig6b-matlab"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Fig6b/Chapt9Fig6b_latex",
              "label": "Fig6b-latex"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Fig6b/Chapt9Fig6b_pdf",
              "label": "Fig6b-pdf"
            }
          ]
        },
        {
          "type": "category",
          "label": "🔧 Utility Functions",
          "collapsed": true,
          "items": [
            {
              "type": "doc",
              "id": "utilities/List of QMmatlab programs/List of QMmatlab programs_text",
              "label": "List of QMmatlab programs-text"
            },
            {
              "type": "doc",
              "id": "utilities/ReadMe/ReadMe_text",
              "label": "ReadMe-text"
            },
            {
              "type": "doc",
              "id": "utilities/Solve_schM/Solve_schM_matlab",
              "label": "Solve_schM-matlab"
            },
            {
              "type": "doc",
              "id": "utilities/chempot/chempot_matlab",
              "label": "chempot-matlab"
            },
            {
              "type": "doc",
              "id": "utilities/datainLI/datainLI_text",
              "label": "datainLI-text"
            },
            {
              "type": "doc",
              "id": "utilities/fermi/fermi_matlab",
              "label": "fermi-matlab"
            },
            {
              "type": "doc",
              "id": "utilities/mu/mu_matlab",
              "label": "mu-matlab"
            },
            {
              "type": "doc",
              "id": "utilities/runge4/runge4_matlab",
              "label": "runge4-matlab"
            }
          ]
        },
      ],
    },
    {
      type: 'category',
      label: '🛠️ Developer Guide',
      collapsed: true,
      items: [
        { type: 'doc', id: 'developer-guide/index', label: 'Overview' },
        {
          type: 'category',
          label: 'Configuration',
          collapsed: true,
          items: [
            { type: 'doc', id: 'developer-guide/config/index', label: 'Config Module' },
          ],
        },
        {
          type: 'category',
          label: 'Utilities',
          collapsed: true,
          items: [
            { type: 'doc', id: 'developer-guide/utils/index', label: 'Utils Module' },
          ],
        },
        {
          type: 'category',
          label: 'Generators',
          collapsed: true,
          items: [
            { type: 'doc', id: 'developer-guide/generators/index', label: 'Generators Module' },
          ],
        },
        {
          type: 'category',
          label: 'Services',
          collapsed: true,
          items: [
            { type: 'doc', id: 'developer-guide/services/index', label: 'Services Module' },
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
