/**
 * Auto-generated sidebar configuration
 * Generated by: generate-program-docs.js v2.0
 * Last updated: 2025-12-23T16:46:26.604Z
 *
 * DO NOT EDIT MANUALLY - Changes will be overwritten on next generation
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '📖 Introduction',
    },
    {
      type: 'category',
      label: '📚 Programs by Chapter',
      collapsed: false,
      items: [
        {
          "type": "category",
          "label": "Ch 1: Introduction to Quantum Mechanics",
          "collapsed": true,
          "items": [
            {
              "type": "doc",
              "id": "chapter1/Chapt1Exercise8/index",
              "label": "Exercise 8"
            },
            {
              "type": "doc",
              "id": "chapter1/Chapt1Fig10/index",
              "label": "Fig 10"
            },
            {
              "type": "doc",
              "id": "chapter1/Chapt1Fig8/index",
              "label": "Fig 8"
            }
          ]
        },
        {
          "type": "category",
          "label": "Ch 2: Schrödinger Equation",
          "collapsed": true,
          "items": [
            {
              "type": "doc",
              "id": "chapter2/Chapt2Fig2/index",
              "label": "Fig 2"
            },
            {
              "type": "doc",
              "id": "chapter2/Chapt2Fig24/index",
              "label": "Fig 24"
            },
            {
              "type": "doc",
              "id": "chapter2/Chapt2Fig3a/index",
              "label": "Fig 3A"
            },
            {
              "type": "doc",
              "id": "chapter2/Chapt2Fig3b/index",
              "label": "Fig 3B"
            },
            {
              "type": "doc",
              "id": "chapter2/Chapt2Fig4/index",
              "label": "Fig 4"
            }
          ]
        },
        {
          "type": "category",
          "label": "Ch 3: Quantum Wells and Barriers",
          "collapsed": true,
          "items": [
            {
              "type": "doc",
              "id": "chapter3/Chapt3Exercise7/index",
              "label": "Exercise 7"
            },
            {
              "type": "doc",
              "id": "chapter3/Chapt3Fig14/index",
              "label": "Fig 14"
            }
          ]
        },
        {
          "type": "category",
          "label": "Ch 4: Harmonic Oscillator",
          "collapsed": true,
          "items": [
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise2a/index",
              "label": "Exercise 2A"
            },
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise2b/index",
              "label": "Exercise 2B"
            },
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise3a/index",
              "label": "Exercise 3A"
            },
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise3b/index",
              "label": "Exercise 3B"
            },
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise4a/index",
              "label": "Exercise 4A"
            },
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise4b1/index",
              "label": "Exercise 4B1"
            },
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise4b2/index",
              "label": "Exercise 4B2"
            },
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise4b3/index",
              "label": "Exercise 4B3"
            },
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise5/index",
              "label": "Exercise 5"
            },
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise7a/index",
              "label": "Exercise 7A"
            },
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise7b/index",
              "label": "Exercise 7B"
            },
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise8/index",
              "label": "Exercise 8"
            },
            {
              "type": "doc",
              "id": "chapter4/Chapt4Exercise9/index",
              "label": "Exercise 9"
            }
          ]
        },
        {
          "type": "category",
          "label": "Ch 5: Tunneling and Resonance",
          "collapsed": true,
          "items": [
            {
              "type": "doc",
              "id": "chapter5/Chapt5Exercise5/index",
              "label": "Exercise 5"
            }
          ]
        },
        {
          "type": "category",
          "label": "Ch 6: Density of States",
          "collapsed": true,
          "items": [
            {
              "type": "doc",
              "id": "chapter6/Chapt6Exercise10/index",
              "label": "Exercise 10"
            },
            {
              "type": "doc",
              "id": "chapter6/Chapt6Exercise4c/index",
              "label": "Exercise 4C"
            },
            {
              "type": "doc",
              "id": "chapter6/Chapt6Exercise4d/index",
              "label": "Exercise 4D"
            }
          ]
        },
        {
          "type": "category",
          "label": "Ch 7: Band Structure",
          "collapsed": true,
          "items": [
            {
              "type": "doc",
              "id": "chapter7/Chapt7Exercise3/index",
              "label": "Exercise 3"
            },
            {
              "type": "doc",
              "id": "chapter7/Chapt7Fig3/index",
              "label": "Fig 3"
            },
            {
              "type": "doc",
              "id": "chapter7/Chapt7Fig4a/index",
              "label": "Fig 4A"
            },
            {
              "type": "doc",
              "id": "chapter7/Chapt7Fig4b/index",
              "label": "Fig 4B"
            },
            {
              "type": "doc",
              "id": "chapter7/Chapt7Fig5a/index",
              "label": "Fig 5A"
            },
            {
              "type": "doc",
              "id": "chapter7/Chapt7Fig5b/index",
              "label": "Fig 5B"
            },
            {
              "type": "doc",
              "id": "chapter7/Chapt7Fig6a/index",
              "label": "Fig 6A"
            },
            {
              "type": "doc",
              "id": "chapter7/Chapt7Fig6b/index",
              "label": "Fig 6B"
            }
          ]
        },
        {
          "type": "category",
          "label": "Ch 8: Perturbation Theory",
          "collapsed": true,
          "items": [
            {
              "type": "doc",
              "id": "chapter8/Chapt8Exercise1b/index",
              "label": "Exercise 1B"
            },
            {
              "type": "doc",
              "id": "chapter8/Chapt8Exercise7a/index",
              "label": "Exercise 7A"
            },
            {
              "type": "doc",
              "id": "chapter8/Chapt8Exercise7b/index",
              "label": "Exercise 7B"
            },
            {
              "type": "doc",
              "id": "chapter8/Chapt8Fig14a/index",
              "label": "Fig 14A"
            },
            {
              "type": "doc",
              "id": "chapter8/Chapt8Fig14b/index",
              "label": "Fig 14B"
            },
            {
              "type": "doc",
              "id": "chapter8/Chapt8Fig15/index",
              "label": "Fig 15"
            }
          ]
        },
        {
          "type": "category",
          "label": "Ch 9: Statistical Mechanics",
          "collapsed": true,
          "items": [
            {
              "type": "doc",
              "id": "chapter9/Chapt9Exercise1/index",
              "label": "Exercise 1"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Exercise2/index",
              "label": "Exercise 2"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Exercise3/index",
              "label": "Exercise 3"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Exercise4/index",
              "label": "Exercise 4"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Exercise5/index",
              "label": "Exercise 5"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Fig6a1/index",
              "label": "Fig 6A1"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Fig6a2/index",
              "label": "Fig 6A2"
            },
            {
              "type": "doc",
              "id": "chapter9/Chapt9Fig6b/index",
              "label": "Fig 6B"
            }
          ]
        },
      ],
    },
  ],
};

module.exports = sidebars;
